### ISSUE TITLE
blank to_do list shouldn't be added

### ISSUE THREAD

**Issue by Irtesaam** [Irtesaam/to_do_list#1]
### Steps to reproduce
1. Visit [https://irtesaam.github.io/to_do_list/](url) and click on Add to list button.
2. A blank list will be added.

### Expected behavior
On clicking add to list button for empty list, there should be a warning which says "Please enter the title".

### Current behavior
It adds the empty list

### Screen-recording attached 
https://github.com/user-attachments/assets/0753c551-11bb-4025-a5c9-7fa5225d6911

### System Information
OS Name: Microsoft Windows 11 Home Single Language
OS Version & Build : 10.0.22621

**Comment by FullStackWebDeveloper-HARSH** [comment]
Hi Irtesaam,
I would like to work on this issue. Could you please assign it to me?

Thank you!

Best regards,
Harsh

**Comment by FullStackWebDeveloper-HARSH** [comment]
Hi Irtesaam,

Thank you for assigning this issue to me. I will start working on it right away.

Best regards,
Harsh.

**Comment by FullStackWebDeveloper-HARSH** [comment]
Dear Irtesaam,

I hope this message finds you well. I wanted to inform you that I have recently submitted a Pull Request to your repository to_do_list. The Pull Request aims to enhance functionality of the to-do list application by adding validation to prevent blank entries from being added.

I would greatly appreciate it if you could take some time to review the Pull Request at your earliest convenience. Your feedback and suggestions would be invaluable to improving the quality and functionality of the project.

Thank you for maintaining this open source project and considering my contribution. Looking forward to your feedback.

Best regards,
Harsh.

**Comment by Irtesaam** [comment]
Hello Harsh,

The pull request has been merged.
Thank you for your contribution.
